# Generated by Django 3.1.5 on 2021-01-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.town')),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('ending_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_town', to='timetable.town')),
                ('starting_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_town', to='timetable.town')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('ending_stop', models.ManyToManyField(related_name='end_stop', to='timetable.Stops')),
                ('starting_stop', models.ManyToManyField(related_name='start_stop', to='timetable.Stops')),
            ],
        ),
    ]
