# Generated by Django 3.1.5 on 2021-01-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
        migrations.RenameModel(
            old_name='Lines',
            new_name='Line',
        ),
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
