# Generated by Django 3.1.5 on 2021-01-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210115_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_nr', models.IntegerField()),
                ('time_diff', models.IntegerField(null=True)),
                ('route_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.route')),
                ('stop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.stop')),
            ],
            options={
                'unique_together': {('route_id', 'stop_nr')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend', models.BooleanField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('route_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.route')),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='ending_town',
        ),
        migrations.RemoveField(
            model_name='line',
            name='starting_town',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
