# Generated by Django 3.1.5 on 2021-01-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20210116_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_details',
            name='time',
        ),
    ]
